### PR TITLE
Update aboutus.js

### PR DESCRIPTION
**Pull request by aruba246**

### CODE REVIEW

**Comment by harishnandan** [comment]
@aruba246 The blank space is there so that it can help us to easily distinguish the function and the variables. Also try to create an issue before sending a PR. That would help other members also on the development of the project. For now I am closing this PR.

**Comment by aruba246** [comment]
Is there any Gitter room for Reflexio?If yes please send me the name.I am
unable to find any.

**Comment by harishnandan** [comment]
There is no gitter channel. For communication we are using a facebook group.
https://www.facebook.com/groups/136133120486393/

**Comment by aruba246** [comment]
Where do i add the background music file for Reflexio?Please Guide.

**Pull request closed without merging**
